apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptimehive

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgresql.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: uptimehive
  app.kubernetes.io/managed-by: kustomize
