apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma
  # namespace set by overlay
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/part-of: uptimehive
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
  # namespaceSelector patched by overlay
  namespaceSelector:
    matchNames:
      - placeholder
  endpoints:
    - port: http
      path: /metrics/uptime-hive
      interval: 15s
      scrapeTimeout: 10s
