apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptimehive-staging

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - secret.yaml
  - pre-deploy-backup-job.yaml

# Override image tag for staging
images:
  - name: ghcr.io/tuergeist/uptime-kuma-x
    newTag: staging

# Patch ServiceMonitors to use staging namespace
patches:
  - patch: |-
      - op: replace
        path: /spec/namespaceSelector/matchNames/0
        value: uptimehive-staging
    target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
